
- name: config > File
  lineinfile:
    dest:   "{{ manala_shorewall_config_file }}"
    regexp: "^{{ item.key }}="
    line:   "{{ item.key }}={{ item.value }}"
  with_dict: "{{ manala_shorewall_config }}"
  notify:
    - shorewall restart
