
- name: config > File
  lineinfile:
    dest:   "{{ manala_shorewall_config_file }}"
    regexp: "^{{ item.keys()[0] }}="
    line:   "{{ item.keys()[0] }}={{ item.values()[0] }}"
  with_items: "{{ manala_shorewall_config }}"
  notify:
    - shorewall restart
